### ISSUE TITLE
Provide metadata for pages (used in traits) that aren't in the DH

### ISSUE THREAD

**Issue by jar398** [jar398/plotter#12]
Many pages that aren't in the DH show up in trait records. Without page metadata, these are not useful.  Either suppress these trait records, or add page records as needed to the traits dump.

Reported by Ray Ma

**Comment by jhammock** [comment]
I'm game to suppress these from the traits dump since someone cares enough to want one solution or the other. @KatjaSchulz do you have a preference?

**Comment by KatjaSchulz** [comment]
I think it's ok to suppress them. I am currently working on ways to extend the DH specifically with respect to taxa that turn up in trait data sets, so the number of uncovered taxa should decrease with time.

**Comment by jar398** [comment]
On the beta instance, about 25% of Trait nodes are for Pages that aren't in the DH (2,995,201 out of 12,262,690). Suppressing them will make the dump a little smaller and might make the dump process faster (but I don't know, it could make it slower since the query becomes a little bit more complicated).  I've implemented suppression so it should be effective when Eli picks up this version.

**Comment by jhammock** [comment]
paging @eagbayani in case there's action needed to accept this change, or in case it's a surprise when the traits export shrinks :)

**Comment by jhammock** [comment]
paging @eliagbayani in case action is needed to accept this change or in case it is a surprise when the traits export shrinks. :)

**Comment by jar398** [comment]
This is going to be a major new release of the traits dumper (and my other tools such as branch painting). When I'm done testing I'll move everything to the master branch and give @eliagbayani  upgrade instructions.

**Comment by eliagbayani** [comment]
@jar398 @jhammock , noted. Thanks.

**Comment by jar398** [comment]
I did some simple timings and am fairly confident that suppressing these Page nodes won't slow down the dump process.
