### ISSUE TITLE
Resource metadata

### ISSUE THREAD

**Issue by jar398** [jar398/plotter#7]
* `rake traits:sync_resource_metadata` - works
* Need schema documentation. `repository_id`, `name`, `description`

**Comment by jar398** [comment]
This feature will be much improved if the publishing logic is modified to add the required properties (name and description) to the `Resource` nodes on each publish.  If this isn't done already I wonder if I can ask @mvitale if he's willing to make the modification to eol_website.

**Comment by jhammock** [comment]
Yes, there are good use cases for that too. I'll put that on MV's list

**Comment by mvitale** [comment]
This is committed per the referenced issue

**Comment by jar398** [comment]
I have not tested this directly but trust that it is done, so will close this issue too. Thanks @mvitale

**Comment by mvitale** [comment]
Note that we still need to deploy/run the script for the properties to be populated in beta/production.

**Comment by jar398** [comment]
oh yeah

**Comment by jar398** [comment]
done
