### ISSUE TITLE
Adapt traits dumping code to recent MV trait schema updates

### ISSUE THREAD

**Issue by jar398** [jar398/plotter#8]
* Find out what the changes are (Dec 2019 to Aug 2020) with
    * `(cd ../eol_website; git diff e4d4ba69 95b17579 -- doc/trait-schema.md) >schema-diff.tmp`
* change `object_page_id` to `object_page`
* new properties: `citation`, `method`, `remarks`, `sample_size`,
  `name_`languagecode, `trait_row_count`, `distinct_page_count` ...
* `object_for_predicate` - do not capture?

**Comment by jhammock** [comment]
indeed, object_for_predicate helps speed up some queries in the search page; it is not needed here.

**Comment by jar398** [comment]
Actually I wonder if all the 'denormalized' properties can be omitted, i.e. they don't need columns in the traits dump?  Anyone who cares can get the information from the MetaData table in the dump.  I'm not sure exactly which properties this applies to. Will have to do some research to verify this hypothesis, but it's possible I don't need to make any changes at all here.

**Comment by mvitale** [comment]
Of the above properties, trait_row_count, distinct_page_count and object_for_predicate should be omitted. I'm not sure if you want to dump all of the Term name translations -- those are potentially subject to change -- but it's up to you.

**Comment by jar398** [comment]
Done as far as I can tell
