### ISSUE TITLE
Chunkify vernaculars loading

### ISSUE THREAD

**Issue by jar398** [jar398/plotter#9]
Loading wikidata vernaculars was timing out ... I think this is fixed now?

**Comment by jhammock** [comment]
yes, this harvested and published successfully last try.

**Comment by jar398** [comment]
Oh sorry, I meant loading them using my script that loads them into the graphdb.  This is becoming moot now that @mvitale has implemented vernaculars-to-graphdb as part of publishing, but I thought it might be of some use for other already-published resources?

**Comment by jhammock** [comment]
oh, I see- no, I don't think we'll need any more migrations if wikidata published alright, thanks. There are only a handful of other, smaller sources of vernaculars.

**Comment by jar398** [comment]
I believe that this works now, even if it is moot.
